version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: product_catalog_db_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_catalog_db
    ports:
      - '5432:5432'
    volumes:
      - product_catalog_data:/var/lib/postgresql/data

volumes:
  product_catalog_data:
